### ISSUE TITLE
Update Bootstrap to v5.1.x

### ISSUE THREAD

**Issue by tim-breitenstein-it** [patriceckhart/NeosRulez.Bootstrap#7]
Is it possible to update Bootstrap to the latest release?

https://blog.getbootstrap.com/2021/09/07/bootstrap-5-1-1/

https://getbootstrap.com/docs/5.1/getting-started/introduction/

**Comment by patriceckhart** [comment]
I haven't integrated the last release yet, but I'll do it asap. But you can load the latest resources via your site package and use NeosRulez.Bootstrap for templates and NodeTypes.
