### ISSUE TITLE
Navbar: Parent page of dropdown accessible?

### ISSUE THREAD

**Issue by bbtimx** [patriceckhart/NeosRulez.Bootstrap#8]
Is it possible to make the parent page of an dropdown menu accessible?

Pages:

- Page 1
- Page 2
  - Child Page 2.1
  - Child Page 2.2
- Page 2

At the monent the Page 2 ist not accessable via navbar menu.

**Comment by patriceckhart** [comment]
Yes, that is possible. Look in the Settings.yaml and activate e.g. clickableParent ...

```
NeosRulez:
  Bootstrap:
    clickableParent: true
```
